# Generated by Django 4.0.3 on 2022-04-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Migration1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_source', models.CharField(max_length=100)),
                ('db_user', models.CharField(max_length=100)),
                ('db_passwd', models.CharField(max_length=100)),
                ('db_host', models.CharField(max_length=100)),
                ('db_port', models.IntegerField()),
                ('db_service_name', models.CharField(max_length=100)),
            ],
        ),
    ]
