# Generated by Django 4.0.3 on 2022-04-05 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='migration1',
            old_name='db_host',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='migration1',
            old_name='db_passwd',
            new_name='passwd',
        ),
        migrations.RenameField(
            model_name='migration1',
            old_name='db_port',
            new_name='port',
        ),
        migrations.RenameField(
            model_name='migration1',
            old_name='db_service_name',
            new_name='service_name',
        ),
        migrations.RenameField(
            model_name='migration1',
            old_name='db_source',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='migration1',
            old_name='db_user',
            new_name='user',
        ),
    ]
